[package]
name = "rs_raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
crossbeam-utils = "0.8.5"
iter_fixed = "0.3.1"